using System.Collections.Immutable;
using System.Text;

namespace MimironSQL.DbContextGenerator;

internal static class GeneratedCodeRenderer
{
    public static string RenderReadHelpers(string rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using CASC.Net.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("internal static class Db2GeneratedReadHelpers");
        sb.AppendLine("{");
        sb.AppendLine("    internal static T[] ReadStructArray<T>(DbcdRow row, string baseFieldName, int length) where T : struct");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new T[length];");
        sb.AppendLine("        for (var i = 0; i < length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            result[i] = row.Get<T>($\"{baseFieldName}[{i}]\");");
        sb.AppendLine("        }");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static string[] ReadStringArray(DbcdRow row, string baseFieldName, int length)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = new string[length];");
        sb.AppendLine("        for (var i = 0; i < length; i++)");
        sb.AppendLine("            result[i] = row.Get<string>($\"{baseFieldName}[{i}]\") ?? string.Empty;");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string RenderRow(string rootNamespace, TableSpec table)
    {
        var safeTableName = IdentifierHelper.ToSafeTypeName(table.TableName);        

        var rowType = $"{safeTableName}";
        var materializerType = $"{safeTableName}Materializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CASC.Net.Abstractions;");
        sb.AppendLine("using CASC.Net.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();

        var columnProperties = GetUniquePropertyNames(table.Columns, safeTableName);
        var layouts = DbdLayoutSynthesis.Create(table, columnProperties);
        var maxArrays = DbdLayoutSynthesis.ComputeMaxArrayLengths(table);

        var presentInAllLayouts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (layouts.Length > 0)
        {
            presentInAllLayouts.UnionWith(table.Columns.Select(static c => c.Name));
            foreach (var layout in layouts)
            {
                var set = new HashSet<string>(layout.PhysicalColumns.Select(static c => c.DbdName), StringComparer.OrdinalIgnoreCase);
                presentInAllLayouts.RemoveWhere(name => !set.Contains(name));
            }
        }
        else
        {
            // No parsed version info; treat all columns as present.
            presentInAllLayouts.UnionWith(table.Columns.Select(static c => c.Name));
        }

        string GetEntityCSharpType(ColumnSpec col)
        {
            var element = TypeMapping.GetCSharpElementType(col.DbdType);
            var isArray = maxArrays.MaxByColumnName.TryGetValue(col.Name, out _);
            var baseType = isArray ? element + "[]" : element;
            var isOptional = !presentInAllLayouts.Contains(col.Name);

            if (!isOptional)
                return baseType;

            if (isArray || element == "string")
                return baseType + "?";

            return baseType + "?";
        }

        sb.AppendLine($"public readonly partial record struct {rowType}(");
        for (var i = 0; i < table.Columns.Length; i++)
        {
            var col = table.Columns[i];
            var csType = GetEntityCSharpType(col);
            var propName = columnProperties[i];

            var suffix = i == table.Columns.Length - 1 ? ")" : ",";
            sb.AppendLine($"    {csType} {propName}{suffix}");
        }

        sb.AppendLine();
        sb.AppendLine("{");

        // Per-layout marker types allow multiple layout constructors even when the physical column
        // sequences have identical CLR type signatures (parameter names alone do not disambiguate overloads).
        for (var layoutIndex = 0; layoutIndex < layouts.Length; layoutIndex++)
            sb.AppendLine($"    internal readonly struct __Db2Layout{layoutIndex} {{ }}");
        if (layouts.Length > 0)
            sb.AppendLine();

        // One constructor per distinct physical layout.
        for (var layoutIndex = 0; layoutIndex < layouts.Length; layoutIndex++)
        {
            var layout = layouts[layoutIndex];
            sb.AppendLine($"    internal {rowType}(");
            if (layout.PhysicalColumns.Length == 0)
            {
                sb.AppendLine($"        __Db2Layout{layoutIndex} _)");
            }
            else
            {
                sb.AppendLine($"        __Db2Layout{layoutIndex} _,");
                for (var i = 0; i < layout.PhysicalColumns.Length; i++)
                {
                    var pc = layout.PhysicalColumns[i];
                    var element = TypeMapping.GetCSharpElementType(pc.DbdType);
                    var paramType = pc.ArrayLength is not null ? element + "[]" : element;
                    var suffix = i == layout.PhysicalColumns.Length - 1 ? ")" : ",";
                    sb.AppendLine($"        {paramType} {pc.PropertyName}{suffix}");
                }
            }

            sb.AppendLine("        : this(");

            var presentMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var pc in layout.PhysicalColumns)
                presentMap[pc.DbdName] = pc.PropertyName;

            for (var i = 0; i < table.Columns.Length; i++)
            {
                var col = table.Columns[i];
                var propName = columnProperties[i];
                var element = TypeMapping.GetCSharpElementType(col.DbdType);
                var isArray = maxArrays.MaxByColumnName.TryGetValue(col.Name, out _);
                var isOptional = !presentInAllLayouts.Contains(col.Name);

                string arg;
                if (presentMap.TryGetValue(col.Name, out var paramName))
                {
                    arg = paramName;
                }
                else
                {
                    if (isOptional)
                        arg = "null";
                    else if (isArray || element == "string")
                        arg = element == "string" ? "string.Empty" : $"new {element}[0]";
                    else
                        arg = "default";
                }

                var suffix = i == table.Columns.Length - 1 ? ")" : ",";
                sb.AppendLine($"            {arg}{suffix}");
            }

            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        sb.AppendLine("    public static Db2GeneratedTableSchema __Db2TableSchema { get; } = ");
        sb.AppendLine("        new(");
        sb.AppendLine($"            \"{EscapeString(table.TableName)}\",");
        sb.AppendLine("            new Db2GeneratedLayoutSchema[]");
        sb.AppendLine("            {");
        for (var i = 0; i < layouts.Length; i++)
        {
            var layout = layouts[i];
            sb.AppendLine("                new(");
            sb.AppendLine("                    new Db2GeneratedBuildConstraint[]");
            sb.AppendLine("                    {");

            foreach (var bc in layout.BuildConstraints)
            {
                if (bc is DbdLayoutSynthesis.BuildConstraint.Exact exact)
                    sb.AppendLine($"                        new Db2GeneratedBuildConstraint.Exact(WowBuildVersion.Parse(\"{EscapeString(exact.Version)}\")),");
                else if (bc is DbdLayoutSynthesis.BuildConstraint.Range range)
                    sb.AppendLine($"                        new Db2GeneratedBuildConstraint.Range(WowBuildVersion.Parse(\"{EscapeString(range.From)}\"), WowBuildVersion.Parse(\"{EscapeString(range.To)}\")),");
            }

            sb.AppendLine("                    },");
            sb.AppendLine("                    new Db2GeneratedRowSchema(");
            sb.AppendLine($"                        \"{EscapeString(table.TableName)}\",");
            sb.AppendLine("                        new Db2GeneratedColumnSchema[]");
            sb.AppendLine("                        {");

            foreach (var col in layout.PhysicalColumns)
            {
                var arrayLengthExpr = col.ArrayLength is { } len ? len.ToString() : "null";
                sb.AppendLine($"                            new(\"{EscapeString(col.DbdName)}\", \"{EscapeString(col.PropertyName)}\", \"{EscapeString(col.DbdType)}\", {arrayLengthExpr}),");
            }

            sb.AppendLine("                        })");
            sb.AppendLine(i == layouts.Length - 1 ? "                )" : "                ),");
        }

        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine($"    internal static {rowType} From(DbcdRow row)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (row is null) throw new ArgumentNullException(nameof(row));");
        sb.AppendLine();
        sb.AppendLine($"        return new {rowType}(");

        for (var i = 0; i < table.Columns.Length; i++)
        {
            var col = table.Columns[i];
            var fieldName = EscapeString(col.Name);

            var elementType = TypeMapping.GetCSharpElementType(col.DbdType);
            var isOptional = !presentInAllLayouts.Contains(col.Name);

            string expr;
            if (maxArrays.MaxByColumnName.TryGetValue(col.Name, out var maxLen))
            {
                var presenceCheck = elementType == "string"
                    ? $"row[\"{fieldName}[0]\"]"
                    : $"row[\"{fieldName}[0]\"]";

                var readExpr = elementType == "string"
                    ? $"Db2GeneratedReadHelpers.ReadStringArray(row, \"{fieldName}\", {maxLen})"
                    : $"Db2GeneratedReadHelpers.ReadStructArray<{elementType}>(row, \"{fieldName}\", {maxLen})";

                expr = isOptional
                    ? $"{presenceCheck} is null ? null : {readExpr}"
                    : readExpr;
            }
            else
            {
                if (elementType == "string")
                {
                    var get = $"row.Get<string>(\"{fieldName}\")";
                    expr = isOptional ? get : $"{get} ?? string.Empty";
                }
                else
                {
                    var get = $"row.Get<{elementType}>(\"{fieldName}\")";
                    expr = isOptional ? $"row[\"{fieldName}\"] is null ? ({elementType}?)null : {get}" : get;
                }
            }

            var suffix = i == table.Columns.Length - 1 ? ");" : ",";
            sb.AppendLine($"            {expr}{suffix}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        sb.AppendLine();
        sb.AppendLine($"internal sealed class {materializerType} : IDb2RowMaterializer<{rowType}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IDb2RowMaterializer<DbcdRow> _inner;");
        sb.AppendLine();
        sb.AppendLine($"    public {materializerType}(IDb2RowMaterializer<DbcdRow> inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public async ValueTask<IReadOnlyList<{rowType}>> LoadAsync(IDb2DataSource dataSource, Db2TableMetadata metadata, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var rows = await _inner.LoadAsync(dataSource, metadata, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine($"        var result = new List<{rowType}>(rows.Count);");
        sb.AppendLine("        foreach (var row in rows)");
        sb.AppendLine($"            result.Add({rowType}.From(row));");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string RenderContext(string rootNamespace, ImmutableArray<TableSpec> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using CASC.Net.Abstractions;");
        sb.AppendLine("using CASC.Net.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class WowDb2Context : Db2Context");
        sb.AppendLine("{");
        sb.AppendLine("    public WowDb2Context(IDb2DataSource dataSource, IDb2TableFactory tableFactory)");
        sb.AppendLine("        : base(dataSource, tableFactory)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var table in tables)
        {
            var safeTableName = IdentifierHelper.ToSafeTypeName(table.TableName);
            var memberName = IdentifierHelper.ToSafeMemberName(table.TableName);
            var rowType = $"{safeTableName}";
            var rowFullName = $"{rootNamespace}.{rowType}";

            var baseMetadataExpr = $"new Db2TableMetadata(\"{EscapeString(table.TableName)}\", {table.FileDataId})";

            var hasIntKey = TryGetSingleIntKeyPropertyName(table, out var keyPropertyName);
            var createSetPrefix = $"CreateSet<{rowFullName}>(";

            string createSetSuffix;
            if (hasIntKey)
            {
                createSetSuffix = $", static r => r.{keyPropertyName})";
            }
            else
            {
                createSetSuffix = ")";
            }

            if (table.ForeignKeys.Length == 0)
            {
                sb.AppendLine($"    public Db2Set<{rowFullName}> {memberName} => {createSetPrefix}{baseMetadataExpr}, {rowFullName}.__Db2TableSchema, static row => {rowFullName}.From(row){createSetSuffix};");
                continue;
            }

            sb.AppendLine($"    public Db2Set<{rowFullName}> {memberName} => {createSetPrefix}");
            sb.AppendLine($"        {baseMetadataExpr}");
            sb.AppendLine("        {");
            sb.AppendLine("            ForeignKeys = new Db2ForeignKeyMetadata[]");
            sb.AppendLine("            {");

            foreach (var fk in table.ForeignKeys)
            {
                sb.AppendLine($"                new(\"{EscapeString(fk.ColumnName)}\", \"{EscapeString(fk.TargetTableName)}\", \"{EscapeString(fk.TargetColumnName)}\"),");
            }

            sb.AppendLine("            },");
            sb.AppendLine("        },");
            sb.AppendLine($"        {rowFullName}.__Db2TableSchema,");
            sb.AppendLine($"        static row => {rowFullName}.From(row){createSetSuffix};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string RenderServiceCollectionExtensions(string rootNamespace, ImmutableArray<TableSpec> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using CASC.Net.Abstractions;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("public static class Db2GeneratedServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddCascNetDb2Generated(this IServiceCollection services)");
        sb.AppendLine("    {");

        sb.AppendLine("        services.TryAddSingleton<WowDb2Context>();");

        foreach (var table in tables)
        {
            var safeTableName = IdentifierHelper.ToSafeTypeName(table.TableName);
            var rowType = $"{rootNamespace}.{safeTableName}";
            var matType = $"{rootNamespace}.{safeTableName}Materializer";

            sb.AppendLine($"        services.TryAddSingleton<IDb2RowMaterializer<{rowType}>, {matType}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string[] GetUniquePropertyNames(ImmutableArray<ColumnSpec> columns, string enclosingTypeName)
    {
        static string IdentifierKey(string identifier)
            => identifier.StartsWith("@", StringComparison.Ordinal) ? identifier.Substring(1) : identifier;

        var used = new HashSet<string>(StringComparer.Ordinal);

        // Avoid generating members that conflict with the enclosing type name (CS0542),
        // and with the explicit members we emit ourselves.
        used.Add(IdentifierKey(enclosingTypeName));
        used.Add("From");
        var result = new string[columns.Length];

        for (var i = 0; i < columns.Length; i++)
        {
            var baseName = IdentifierHelper.ToSafeMemberName(columns[i].Name);

            // C# forbids a member having the same name as its enclosing type.
            // Example: record struct ArtifactTier(int ArtifactTier, ...) -> CS0542.
            if (string.Equals(IdentifierKey(baseName), enclosingTypeName, StringComparison.Ordinal))
                baseName = enclosingTypeName + "Value";

            var name = baseName;

            var n = 2;
            while (!used.Add(IdentifierKey(name)))
            {
                name = baseName + "_" + n;
                n++;
            }

            result[i] = name;
        }

        return result;
    }

    private static bool TryGetSingleIntKeyPropertyName(TableSpec table, out string propertyName)
    {
        propertyName = string.Empty;

        var safeTableName = IdentifierHelper.ToSafeTypeName(table.TableName);
        var columnPropertyNames = GetUniquePropertyNames(table.Columns, safeTableName);

        // If the key column is missing in any layout, the generated entity property becomes nullable.
        // In that case we must not emit a key selector (CreateSet expects a non-nullable int key).
        var layouts = DbdLayoutSynthesis.Create(table, columnPropertyNames);
        var presentInAllLayouts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (layouts.Length > 0)
        {
            presentInAllLayouts.UnionWith(table.Columns.Select(static c => c.Name));
            foreach (var layout in layouts)
            {
                var set = new HashSet<string>(layout.PhysicalColumns.Select(static c => c.DbdName), StringComparer.OrdinalIgnoreCase);
                presentInAllLayouts.RemoveWhere(name => !set.Contains(name));
            }
        }
        else
        {
            // No parsed version info; treat all columns as present.
            presentInAllLayouts.UnionWith(table.Columns.Select(static c => c.Name));
        }

        if (table.Keys.Length == 0)
        {
            // WoWDBDefs does not consistently include an explicit KEYS section.
            // Many tables still use the conventional int "ID" column as the primary key.
            for (var i = 0; i < table.Columns.Length; i++)
            {
                var col = table.Columns[i];
                if (!string.Equals(col.Name, "ID", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!presentInAllLayouts.Contains(col.Name))
                    return false;

                if (col.ArrayLength is not null)
                    return false;

                if (TypeMapping.GetCSharpElementType(col.DbdType) != "int")
                    return false;

                propertyName = columnPropertyNames[i];
                return true;
            }

            return false;
        }

        var firstKey = table.Keys[0];
        if (firstKey.ColumnNames.Length != 1)
            return false;

        var keyColumnName = firstKey.ColumnNames[0];
        if (string.IsNullOrWhiteSpace(keyColumnName))
            return false;

        for (var i = 0; i < table.Columns.Length; i++)
        {
            var col = table.Columns[i];
            if (!string.Equals(col.Name, keyColumnName, StringComparison.OrdinalIgnoreCase))
                continue;

            if (!presentInAllLayouts.Contains(col.Name))
                return false;

            if (col.ArrayLength is not null)
                return false;

            if (TypeMapping.GetCSharpElementType(col.DbdType) != "int")
                return false;

            propertyName = columnPropertyNames[i];
            return true;
        }

        return false;
    }
}
